/*
  DhunDhun product catalog.
  ------------------------------------------------------------
  Generated by the admin dashboard (admin.html). Replace the old
  js/products-data.js in your project with this file, then redeploy
  your site so visitors see these changes.

  audiences: "kids" | "students" | "loved-ones" | "artists" | "everyone" | "corporate"
  type: a short category label used for the type filter on the shop page.
  quantity: units in stock. 0 or less shows an "Out of Stock" tag on the site.
*/

const PRODUCTS = [
  {
    "id": "p01",
    "name": "Sakura Bloom Tote Bag",
    "type": "Bags",
    "audiences": [
      "students",
      "loved-ones",
      "everyone"
    ],
    "price": 899,
    "quantity": 24,
    "tag": "Bestseller",
    "description": "Canvas tote with soft pastel cherry-blossom print, roomy enough for campus or daily carry."
  },
  {
    "id": "p02",
    "name": "Kawaii Cloud Sling Bag",
    "type": "Bags",
    "audiences": [
      "students",
      "everyone"
    ],
    "price": 749,
    "quantity": 0,
    "tag": "New",
    "description": "Compact sling bag with plush cloud charm, perfect for daily essentials on the go."
  },
  {
    "id": "p03",
    "name": "Seoul Streets Backpack",
    "type": "Bags",
    "audiences": [
      "students",
      "everyone"
    ],
    "price": 1299,
    "quantity": 15,
    "tag": "",
    "description": "Minimal Korean-style backpack with laptop sleeve, ideal for school and college."
  },
  {
    "id": "p04",
    "name": "Ribbon Diary & Sticker Set",
    "type": "Stationery",
    "audiences": [
      "students",
      "artists",
      "loved-ones"
    ],
    "price": 349,
    "quantity": 40,
    "tag": "Bestseller",
    "description": "Hardbound diary with pastel ribbon bookmark plus 3 sheets of Japanese-style stickers."
  },
  {
    "id": "p05",
    "name": "Cloud Gel Pen Set (6 pcs)",
    "type": "Stationery",
    "audiences": [
      "students",
      "kids"
    ],
    "price": 249,
    "quantity": 55,
    "tag": "",
    "description": "Smooth-writing pastel gel pens with cloud-shaped caps, great for notes and journaling."
  },
  {
    "id": "p06",
    "name": "Origami Geometry Box",
    "type": "Stationery",
    "audiences": [
      "students",
      "kids"
    ],
    "price": 399,
    "quantity": 18,
    "tag": "",
    "description": "Full geometry set in a fold-out origami-print case, exam-season essential."
  },
  {
    "id": "p07",
    "name": "Mochi Friends Pencil Pouch",
    "type": "Stationery",
    "audiences": [
      "kids",
      "students"
    ],
    "price": 279,
    "quantity": 30,
    "tag": "New",
    "description": "Squishy mochi-character pencil pouch with double zip compartments."
  },
  {
    "id": "p08",
    "name": "Chibi Character Keychain",
    "type": "Keychains",
    "audiences": [
      "kids",
      "students",
      "loved-ones",
      "everyone"
    ],
    "price": 149,
    "quantity": 60,
    "tag": "Bestseller",
    "description": "Soft acrylic chibi charm keychain, a small gift that always brings a smile."
  },
  {
    "id": "p09",
    "name": "Anime Buddy Bag Charm Set",
    "type": "Keychains",
    "audiences": [
      "students",
      "everyone"
    ],
    "price": 199,
    "quantity": 33,
    "tag": "",
    "description": "Set of 3 mini anime-style charms to clip onto bags, pouches or keys."
  },
  {
    "id": "p10",
    "name": "Pastel Cloud Desk Lamp",
    "type": "Desk Decor",
    "audiences": [
      "students",
      "artists",
      "loved-ones"
    ],
    "price": 899,
    "quantity": 12,
    "tag": "New",
    "description": "Soft-glow LED cloud lamp that brings cozy kawaii light to any study or work desk."
  },
  {
    "id": "p11",
    "name": "Kawaii Desk Organizer Set",
    "type": "Desk Decor",
    "audiences": [
      "students",
      "artists",
      "everyone"
    ],
    "price": 599,
    "quantity": 20,
    "tag": "",
    "description": "Pastel multi-slot organizer for pens, sticky notes and small desk clutter."
  },
  {
    "id": "p12",
    "name": "Watercolor Artist Sketch Kit",
    "type": "Art Supplies",
    "audiences": [
      "artists",
      "students"
    ],
    "price": 799,
    "quantity": 16,
    "tag": "Bestseller",
    "description": "36-shade watercolor set with sketchbook, built for doodlers and illustrators."
  },
  {
    "id": "p13",
    "name": "Coloring Book: Dreamy Japan",
    "type": "Art Supplies",
    "audiences": [
      "artists",
      "kids"
    ],
    "price": 349,
    "quantity": 25,
    "tag": "",
    "description": "Illustrated coloring book inspired by Japanese streets, gardens and festivals."
  },
  {
    "id": "p14",
    "name": "Mini Diecast Car Collectible",
    "type": "Toys & Collectibles",
    "audiences": [
      "kids"
    ],
    "price": 199,
    "quantity": 45,
    "tag": "",
    "description": "Alloy diecast model car, a favorite pick for young collectors."
  },
  {
    "id": "p15",
    "name": "RC Stunt Car",
    "type": "Toys & Collectibles",
    "audiences": [
      "kids"
    ],
    "price": 1499,
    "quantity": 0,
    "tag": "New",
    "description": "Remote-control stunt car with 360° spins, a birthday party favorite."
  },
  {
    "id": "p16",
    "name": "Plush Character Keyring Duo",
    "type": "Toys & Collectibles",
    "audiences": [
      "kids",
      "loved-ones"
    ],
    "price": 249,
    "quantity": 28,
    "tag": "",
    "description": "Two tiny plush buddies on a keyring, soft and huggable."
  },
  {
    "id": "p17",
    "name": "Love Notes Jar",
    "type": "Gifts",
    "audiences": [
      "loved-ones"
    ],
    "price": 449,
    "quantity": 22,
    "tag": "Bestseller",
    "description": "A jar of 50 handwritten-style note cards to say what words alone can't."
  },
  {
    "id": "p18",
    "name": "Couple Matching Mug Set",
    "type": "Gifts",
    "audiences": [
      "loved-ones"
    ],
    "price": 699,
    "quantity": 14,
    "tag": "",
    "description": "Pastel matching mugs with cute character prints for two."
  },
  {
    "id": "p19",
    "name": "Surprise Gift Hamper",
    "type": "Gifts",
    "audiences": [
      "loved-ones",
      "everyone"
    ],
    "price": 1199,
    "quantity": 10,
    "tag": "New",
    "description": "Curated hamper of stationery, a keychain and a sweet treat, ready to gift."
  },
  {
    "id": "p20",
    "name": "Corporate Welcome Kit",
    "type": "Corporate",
    "audiences": [
      "corporate"
    ],
    "price": 1499,
    "quantity": 50,
    "tag": "Bulk Orders",
    "description": "Branded notebook, pen and tote bundle for onboarding new hires — customizable with your logo."
  },
  {
    "id": "p21",
    "name": "Festive Corporate Hamper",
    "type": "Corporate",
    "audiences": [
      "corporate"
    ],
    "price": 1999,
    "quantity": 35,
    "tag": "Bulk Orders",
    "description": "Diwali / New Year client and employee hamper, customizable packaging and branding."
  },
  {
    "id": "p22",
    "name": "Desk Essentials Corporate Set",
    "type": "Corporate",
    "audiences": [
      "corporate"
    ],
    "price": 899,
    "quantity": 40,
    "tag": "Bulk Orders",
    "description": "Minimal desk organizer + pen set for bulk client or employee gifting."
  },
  {
    "id": "p1784807576167",
    "name": "GT Bags",
    "type": "Bags",
    "price": 450,
    "quantity": 20,
    "tag": "New",
    "description": "Testing",
    "audiences": [
      "kids",
      "students",
      "corporate"
    ]
  },
  {
    "id": "p1784808269383",
    "name": "GT Bag",
    "type": "Bags",
    "price": 450,
    "quantity": 15,
    "tag": "New",
    "description": "Testing",
    "audiences": [
      "kids",
      "students"
    ]
  }
];

const AUDIENCE_LABELS = {
  "kids": "For Kids",
  "students": "For Students",
  "loved-ones": "For Loved Ones",
  "artists": "For Artists",
  "everyone": "For Everyone",
  "corporate": "Corporate Gifting"
};
